### ISSUE TITLE
本地能正常生成二维码，但部署上coding/github为何都是404页面？

### ISSUE THREAD

**Issue by gcusky** [yscoder/hexo-helper-qrcode#2]
如题，使用的是yeele主题，访问页面 gcusky.coding.me

**Comment by yscoder** [comment]
有没有在线仓库？

**Comment by gcusky** [comment]
https://github.com/gcusky/gcusky.github.io

需要编译前的源码不？

**Comment by yscoder** [comment]
嗯，就是看编译前的

**Comment by gcusky** [comment]
用[hexo-git-backup](https://github.com/coneycode/hexo-git-backup)备份的在线仓库可以不？
我放在coding上，请问您是否有coding账户。要不我直接发你邮箱？

**Comment by yscoder** [comment]
coding 可以

**Comment by gcusky** [comment]
coding放在私人库，我没你coding账号拉不进去😅
我放在存储云上你可以直接下载，麻烦您了，谢谢~
http://cloud.gcusky.com/blog/gcusky-back-gcusky-master.zip

**Comment by gcusky** [comment]
二维码的配置我写在
`back-gcusky/themes/yelee/layout/_partial/right-col.ejs`
里面，方便你查找~
```
<div class="right-wrap">
  <div class="other">
    <p>test of gcusky</p>
  </div>
  <div class="qrcode">
    <p>本页二维码</p>
    <img src="<%- qrcode(url, {
          margin: 2,
    }) %>" height="160" width="160">
  </div>
  <script>
    $(window).scroll(function()
    { 
      //qrcode跟随滚动
      var h = $(window).height();
      var top = $(window).scrollTop();
      var right = $('.right-wrap .other');
      var rightHeight = right.height();
      var qrcode = $('.qrcode').prev().offset();
      var fixedTop = qrcode.top;
      console.log(h+" "+top+" "+fixedTop+" "+rightHeight);
        if(top>=rightHeight+30)
        {
          $('.qrcode').css({'position':'fixed','top': 0,'width': right.width()+'px'});
        }
        else
        {
          $('.qrcode').css({'position':'static', 'top':0,'width': '100%' });   
        } 
       /* return true;*/
    });
  </script>
</div>
```

**Comment by yscoder** [comment]
我这里没有发现问题。
你在本地生成后到 `public/index.html` 中，找到二维码的 `base64` 代码复制到浏览器地址栏扫描看看地址是否正确。如果这里没有问题，那就是你的代码同步有问题。

**Comment by gcusky** [comment]
嗯，我再重新 `clean/generate/deploy` 之后，要么都是 `404`，要么都是 `aboutme` 页面😂~
查看 `hexo g` 生成的 `public` 文件内所有生成的静态页面二维码 `base64` 都是相同的。
应该是提交git部署前 `hexo g` 出了问题，在两台电脑尝试过都这样~请问你是否有这种情况出现。
没有的话可能是我用的主题问题……

**Comment by yscoder** [comment]
你的主题也没有问题，我是把你的主题放到我本地 `themes` 中测试的。我也看了你的 `hexo/config.yml`，没看出来配置有什么问题。你可以试试初始化一个新的 hexo 项目把主题放进去看看。

**Comment by gcusky** [comment]
重新初始化了，生成的静态页还是404二维码，这里是我的整个环境
http://cloud.gcusky.com/blog/hexo-yelee-qrcode.zip
可以在你那边本地`hexo g`一下是否也是如此~

**Comment by yscoder** [comment]
是你的模版缓存问题，导致二维码所在的模版只编译了一次，之后就不在动态编译了，所以 URL 一直是第一次匹配到的文件的 URL。

``` ejs
<!-- 你原来的 -->
<!--<%- partial('_partial/right-col', null, {cache: !config.relative_link}) %>-->

<!-- 改成这样 -->
<%- partial('_partial/right-col') %>
```

**Comment by gcusky** [comment]
好的，非常感谢😆！
自己的粗心占用你的时间了~
